"""add store timezone and geofence

Revision ID: 2145dee4380c
Revises: 4a847fd7ea51
Create Date: 2026-01-02 03:29:19.554464

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2145dee4380c'
down_revision: Union[str, Sequence[str], None] = '4a847fd7ea51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stores', sa.Column('timezone', sa.String(length=64), nullable=False))
    op.add_column('stores', sa.Column('geofence_lat', sa.Float(), nullable=True))
    op.add_column('stores', sa.Column('geofence_lng', sa.Float(), nullable=True))
    op.add_column('stores', sa.Column('geofence_radius_m', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stores', 'geofence_radius_m')
    op.drop_column('stores', 'geofence_lng')
    op.drop_column('stores', 'geofence_lat')
    op.drop_column('stores', 'timezone')
    # ### end Alembic commands ###
