"""add membership is_active

Revision ID: 323b2b5fddff
Revises: 3273dd866cea
Create Date: 2026-01-02 11:37:27.270396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '323b2b5fddff'
down_revision: Union[str, Sequence[str], None] = '3273dd866cea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('store_memberships', sa.Column('is_active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('store_memberships', 'is_active')
    # ### end Alembic commands ###
