"""add is_active to stores

Revision ID: 4a847fd7ea51
Revises: a5f1fc908ce7
Create Date: 2026-01-01 07:45:15.493024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a847fd7ea51'
down_revision: Union[str, Sequence[str], None] = 'a5f1fc908ce7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stores', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.alter_column('stores', 'name',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=100),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stores', 'name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)
    op.drop_column('stores', 'is_active')
    # ### end Alembic commands ###
