"""membership is_active + time_entries week_id

Revision ID: 7862ed33e094
Revises: 323b2b5fddff
Create Date: 2026-01-02 23:57:41.177973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7862ed33e094'
down_revision: Union[str, Sequence[str], None] = '323b2b5fddff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('time_entries', sa.Column('week_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'time_entries', 'weeks', ['week_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'time_entries', type_='foreignkey')
    op.drop_column('time_entries', 'week_id')
    # ### end Alembic commands ###
