"""add time entries

Revision ID: c5c546562f6d
Revises: 2424411d9814
Create Date: 2026-01-02 05:16:45.054093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5c546562f6d'
down_revision: Union[str, Sequence[str], None] = '2424411d9814'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('time_entries', sa.Column('employee_id', sa.UUID(), nullable=False))
    op.add_column('time_entries', sa.Column('out_of_zone_duration', sa.Interval(), nullable=True))
    op.add_column('time_entries', sa.Column('is_out_of_zone', sa.Boolean(), nullable=False))
    op.add_column('time_entries', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.drop_constraint(op.f('time_entries_shift_id_fkey'), 'time_entries', type_='foreignkey')
    op.drop_constraint(op.f('time_entries_user_id_fkey'), 'time_entries', type_='foreignkey')
    op.create_foreign_key(None, 'time_entries', 'users', ['employee_id'], ['id'], ondelete='CASCADE')
    op.drop_column('time_entries', 'in_zone')
    op.drop_column('time_entries', 'out_of_zone_minutes')
    op.drop_column('time_entries', 'shift_id')
    op.drop_column('time_entries', 'user_id')
    op.drop_column('time_entries', 'note')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('time_entries', sa.Column('note', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('time_entries', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('time_entries', sa.Column('shift_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('time_entries', sa.Column('out_of_zone_minutes', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('time_entries', sa.Column('in_zone', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'time_entries', type_='foreignkey')
    op.create_foreign_key(op.f('time_entries_user_id_fkey'), 'time_entries', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('time_entries_shift_id_fkey'), 'time_entries', 'shifts', ['shift_id'], ['id'], ondelete='SET NULL')
    op.drop_column('time_entries', 'created_at')
    op.drop_column('time_entries', 'is_out_of_zone')
    op.drop_column('time_entries', 'out_of_zone_duration')
    op.drop_column('time_entries', 'employee_id')
    # ### end Alembic commands ###
