"""add time_entries

Revision ID: c9955e7e3ad6
Revises: bfc16798ee1f
Create Date: 2026-01-02 05:38:35.181800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c9955e7e3ad6'
down_revision: Union[str, Sequence[str], None] = 'bfc16798ee1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('time_entries', sa.Column('out_of_zone_seconds', sa.Integer(), nullable=False))
    op.drop_column('time_entries', 'out_of_zone_duration')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('time_entries', sa.Column('out_of_zone_duration', postgresql.INTERVAL(), autoincrement=False, nullable=True))
    op.drop_column('time_entries', 'out_of_zone_seconds')
    # ### end Alembic commands ###
