"""add availability and leave requests

Revision ID: e7746a8b76dd
Revises: c74b01c4cb13
Create Date: 2026-01-02 10:15:20.381058

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e7746a8b76dd'
down_revision: Union[str, Sequence[str], None] = 'c74b01c4cb13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('availability',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('store_id', sa.UUID(), nullable=False),
    sa.Column('week_id', sa.UUID(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('available_start_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('available_end_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['week_id'], ['weeks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'store_id', 'week_id', 'day', name='uq_availability_emp_store_week_day')
    )
    op.drop_table('availabilities')
    op.drop_constraint(op.f('leave_requests_decided_by_fkey'), 'leave_requests', type_='foreignkey')
    op.create_foreign_key(None, 'leave_requests', 'users', ['decided_by'], ['id'], ondelete='SET NULL')
    op.drop_column('leave_requests', 'leave_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leave_requests', sa.Column('leave_type', sa.VARCHAR(length=30), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'leave_requests', type_='foreignkey')
    op.create_foreign_key(op.f('leave_requests_decided_by_fkey'), 'leave_requests', 'users', ['decided_by'], ['id'])
    op.create_table('availabilities',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('store_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('employee_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('day_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('available', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('start_time', postgresql.TIME(), autoincrement=False, nullable=True),
    sa.Column('end_time', postgresql.TIME(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['users.id'], name=op.f('availabilities_employee_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], name=op.f('availabilities_store_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('availabilities_pkey')),
    sa.UniqueConstraint('store_id', 'employee_id', 'day_date', name=op.f('uq_availability_store_employee_day'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_table('availability')
    # ### end Alembic commands ###
